import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Factory",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: ["favicon.png"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //const [sidebarOpen, setSidebarOpen] = useState(false)

  return (
    <html lang="en" className="h-full bg-black">
      <body className="h-full">{children}</body>
    </html>
  );
}
